a = input()
b = input()
c = input()
d = input()
e = input()
print('Name:%s' % a)
b = int(b)
print('Id:%s' %b)
c = int(c)
d = int(d)
e = int(e)
tot = c+d+e
print('Total:%s' % tot)
ave = int((c+d+e)/3)
print('Average:' +str(ave))
